/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllDocComponent: typeof import('./src/components/Document/AllDocComponent.vue')['default']
    ContentWrap: typeof import('./src/components/ContentWrap/src/ContentWrap.vue')['default']
    DeptDocComponent: typeof import('./src/components/Document/DeptDocComponent.vue')['default']
    Dialog: typeof import('./src/components/Dialog/src/Dialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    ExternalDocComponent: typeof import('./src/components/Document/ExternalDocComponent.vue')['default']
    FavoriteDocComponent: typeof import('./src/components/Document/FavoriteDocComponent.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    IconSelect: typeof import('./src/components/Icon/src/IconSelect.vue')['default']
    InternalDocComponent: typeof import('./src/components/Document/InternalDocComponent.vue')['default']
    LeaveDocComponent: typeof import('./src/components/Document/LeaveDocComponent.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    LoginFormTitle: typeof import('./src/components/Login/LoginFormTitle.vue')['default']
    MeetingDocComponent: typeof import('./src/components/Document/MeetingDocComponent.vue')['default']
    NavBar: typeof import('./src/components/Document/NavBar.vue')['default']
    NavbarComponent: typeof import('./src/components/Document/NavbarComponent.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode/src/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolDocComponent: typeof import('./src/components/Document/SchoolDocComponent.vue')['default']
    SearchBar: typeof import('./src/components/Document/SearchBar.vue')['default']
    TodoComponent: typeof import('./src/components/Document/TodoComponent.vue')['default']
    UserCenterComponent: typeof import('./src/components/User/UserCenterComponent.vue')['default']
    UserSelectForm: typeof import('./src/components/UserSelectForm/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
